### PR TITLE
Add command line interface tool

### PR DESCRIPTION
**Pull request by sirhcel**
Hello Adam,

at first, I'd like to thank you for starting this project! In lack of command line interface for controlling NETIO devices I had written a small Python script a while ago and a few days ago I found out about your project.

My major points for the initial script were:
- Allowing to turn on or off multiple outputs with a single request
- No password data in the process list or shell history
- If I have to supply the password by a file, I could supply all relevant configuration data by a file
    - From the current directory or specified by an argument for controlling multiple devices
    - Given by an environment variable when dealing with only a single device

This is a port and an extension of this script to start the discussion of an integration with. This pull requests depends on https://github.com/netioproducts/PyNetio/pull/2 and therefor currently contains the commits from there as well.

Best regards,

Christian

### CODE REVIEW

**Comment by sirhcel** [comment]
Today I was using PyNetio in test fixtures for unit tests and felt that having a factory creating `Netio` instances from configuration files would ease this process quite a lot. What about moving the relevant code from `cli.py` into a factory in `Device.py`?

After sleeping over the [config file format](https://github.com/netioproducts/PyNetio/pull/3/commits/c9e8906d366002208235b361a3b41b54254e00a2#diff-e60dc2ca01a40e4b8ed8907f148435dbR126) I would switch to Python's `configparser`. The dependency to PyYAML looks a bit like overkill just for a config file.

**Comment by AdamVerner** [comment]
Hey, reworked the CLI arguments a little. I dropped the pyYAML and used configparser instead, so the requirements are as low as possible.

I added the option for `--password` mysql does that, so why couldn't we?. Maybe i'll add warning later.

I'll write some docs for it in the morning and release it to https://test.pypi.org/

**Comment by AdamVerner** [comment]
Released to [test.pypi](https://test.pypi.org/project/Netio/1.0.0/) from devel.

**Comment by sirhcel** [comment]
Hello Adam,

> Hey, reworked the CLI arguments a little.

thank you for taking the initiative! Especially for fixing the entry point so that it could be used with the wrapper from setuptools again. :-)

I'm sorry to report that as of  https://github.com/netioproducts/PyNetio/pull/3/commits/30b567fa0693c123d5c529a9bc956c7732d95ad1 I've got two issues:

* Performing actions on multiple outputs with one invocation of the tool: I would like to have the chance to turn all outputs off at once
* Certificate path resolution relative to the config file: this allows using config files from version control checked out in arbitrary locations

I'm currently struggeling to the the certificate verification up and running for my setup and will have a deeper look at it the the next days to tell you more. After sleeping one more night over the program arguments and learning that the result is always returned as response, what about going for the following style:
```
$ netio --on 1 --toggle 3 4 --off 2 --get
```

* This assumes a configuration file specified by an environment variable (for example `NETIO_CONFIG`) and we also could specify a device in the config's default section.
* You could for example easily turn off all outputs using
    ```
    $ netio --off 1 2 3 4
    ```
* You could just query the current status via
    ```
    $ netio --get
    ```
* This would allow the corner case which just generates network traffic, but do not hurt otherwise
    ```
    $ netio
    ```
I will code this as a propsal the next days.


> I dropped the pyYAML and used configparser instead, so the requirements are as low as possible.

Thank you very much for that!


> I added the option for `--password` mysql does that, so why couldn't we?. Maybe i'll add warning later.

I don't llike this way because it exposes the password to other uses on the system via the process listing which is a security issue for me. I would not support such a usage. But what about using `--password` without an argument for an interactive password prompt (via `input()`)?


> I'll write some docs for it in the morning and release it to https://test.pypi.org/

Thank you!

Have a nice weekend! Best regards,

Christian

**Comment by sirhcel** [comment]
I noticed that I was wrong with my last proposal
> ```
> $ netio --on 1 --toggle 3 4 --off 2 --get
> ```
because the difference between the get and set requests is the HTTP method used (GET versus POST). In this case, the interface should look like
```
$ netio get
$ netio set --on 1 --toggle 3 4 --off 2
```

https://github.com/sirhcel/PyNetio/commit/b1dcf5fc8f31b615d65387c8186d62a19b10cea2 provides CLI parameter demo and there is more to come soon. I'll keep you posted.

**Comment by AdamVerner** [comment]
> Performing actions on multiple outputs with one invocation of the tool: I would like to have the chance to turn all outputs off at once.

Sure, i'll get back at it later on.

> Certificate path resolution relative to the config file: this allows using config files from version control checked out in arbitrary locations

That's my bad, i forgot to put it back again, i'll put it back again.

> I don't like this way because it exposes the password to other uses on the system via the process listing which is a security issue for me. 

I don't see it as an much of an issue, it's great for running scripts.
If process listing is an issue in your application, either use the config or hide your processes from unauthorized users(e.g proc [hidepid](http://man7.org/linux/man-pages/man5/proc.5.html))

> What about using --password without an argument for an interactive password prompt (via input())?

Why don't we have both?  :)


While we're at the ENV variables, we could parse the the password and username from there as well, so we don't force anyone to use --password

## Multiple outputs

> `$ netio set --on 1 --toggle 3 4 --off 2`

I don't like the way with unix switches, what about we do it with multiple sucessive commands?

```
$ netio device SET 1 ON 2 OFF 3 toggle 4 off
```

the spec would then be something like
```
Netio DEVICE [CMD [ID ACTION [ID ACTION...]]
```

To make it a little more complicated we could do `1-4` for range of ID's and `1,3,5` for list of ID's or combination of both like `1-3,5`for 1,2,3,5. But questioning the reality, is there any real use-case for that?


## Shorthands for device

When supplying device for the script, it could be looked up from config, so you could call `netio dev1 GET` or `netio dev2 SET 1 ON` with following config
```ini
[dev1]
url = http://device.tld
[dev2]
user = read
password = secret
url = http://otherDevice.tld
```

which is in my opinion better than empty call to `netio` If you want some implicit device you can always alias it in the shell.

**Comment by sirhcel** [comment]
> I don't see it as an much of an issue, it's great for running scripts.
> If process listing is an issue in your application, either use the config or hide your processes from unauthorized users(e.g proc [hidepid](http://man7.org/linux/man-pages/man5/proc.5.html))

Disabling process listing completely and not exposing credentials to it are two different measures in my opinion. The former approach requires all users to be aware of that and take appropriate measures - the latter requires just the tool not do do so. I believe that the probability of not having senstive data leaked by accident ist way lower in the latter scenario. But hey, I have not opened this pull request for arguing with you. :)

 
> While we're at the ENV variables, we could parse the the password and username from there as well, so we don't force anyone to use --password

That's definitely a good idea.


> > `$ netio set --on 1 --toggle 3 4 --off 2`
> 
> I don't like the way with unix switches, what about we do it with multiple sucessive commands?
> ```
> $ netio device SET 1 ON 2 OFF 3 toggle 4 off
> ```

To be honest, me neither. I just was too lazy to implement the parsing on my own.

Your approach looks great. I would appreciate having the chance to give all commands in lower case, but that's just a call to `lower()` which we should be able to add easily. I will have a look at this the next days.


> To make it a little more complicated we could do `1-4` for range of ID's and `1,3,5` for list of ID's or combination of both like `1-3,5`for 1,2,3,5. But questioning the reality, is there any real use-case for that?

My use case behind having multiple IDs combined with an action is to turn of a complete test setup using multiple outputs. When working with the individual outputs, I' have the time for writing for example `netio DEVICE 1 on 2 toggle 3 off`. But to me it would be great having the chance to turn them all off with `netio DEVICE all off`.

As I have not found a way of getting `ArgumentParser` to handle a sequence of type `[ID ACTION [ID ACTION [...]]`, I bet we have to implement the parsing ourselves. In this case I would start with the special case `all` and leave the rest to future issues/pull requests.


> When supplying device for the script, it could be looked up from config, so you could call `netio dev1 GET` or `netio dev2 SET 1 ON` with following config
> 
> ```ini
> [dev1]
> url = http://device.tld
> [dev2]
> user = read
> password = secret
> url = http://otherDevice.tld
> ```
> 
> which is in my opinion better than empty call to `netio` If you want some implicit device you can always alias it in the shell.

Chapeau, I like this idea! :) And you are absolutely right, an optional device parameter would create ambiguity. Thank you for pointing me at the alias! This will do the trick for my case with a single NETIO device.

**Comment by AdamVerner** [comment]
> Your approach looks great. I would appreciate having the chance to give all commands in lower case, but that's just a call to lower() which we should be able to add easily. I will have a look at this the next days.

Definitely. I was missing just call to `upper()` actually. It's fixed now

> To me it would be great having the chance to turn them all off with `netio DEVICE all off`.

consider it done in 263baf0. 
Little warning, when turning all outputs at once, there will be a spike in the current draw (especially on older devices without [ZCS](https://www.netio-products.com/en/glossary/zcs-zero-current-switching)) that could trigger off your circuit breakers.


 > As I have not found a way of getting ArgumentParser to handle a sequence of type [ID ACTION [ID ACTION [...]], I bet we have to implement the parsing ourselves. 

it could be done with `nargs=+` and then parsing the argument pairs manually. Similarly for GET.

> Chapeau, I like this idea! :) And you are absolutely right, an optional device parameter would create ambiguity. Thank you for pointing me at the alias! This will do the trick for my case with a single NETIO device.

Glad to hear that, I'll get at it rn.

**Comment by AdamVerner** [comment]
Latest version again at https://test.pypi.org/project/Netio/1.0.2/

**Comment by sirhcel** [comment]
> Definitely. I was missing just call to `upper()` actually. It's fixed now
> [...]
> consider it done in [263baf0](https://github.com/netioproducts/PyNetio/commit/263baf0420fd8c9aa512bd7543d0c4e5b619c420).

Thank you for bringing these changes in!


> Little warning, when turning all outputs at once, there will be a spike in the current draw (especially on older devices without [ZCS](https://www.netio-products.com/en/glossary/zcs-zero-current-switching)) that could trigger off your circuit breakers.

Thank you for pointing that out. This could be a trap for young players.


> it could be done with `nargs='+'` and then parsing the argument pairs manually. Similarly for GET.

I added this mode with [8f7513b](https://github.com/sirhcel/PyNetio/commits/8f7513b2257831b585778c2b032e88cf7469e3ee) for `set` and `get`. For `set` I "forged" the argument's meta variable to look like a pair of ID and action, `ArgumentParser` parses a simple list of arguments, this list gets processed into IDs and actions and finally provided as dict for `set_outputs`.

I also added printing stack traces from exceptions with `--verbose` to support development and issue reports.


After sleeping some more nights over the output from `get` I would use spaces (tab as delimiter) as default to improve readability for humans. This works even for the default settings of awk or cut. Please have a look at https://github.com/sirhcel/PyNetio/commit/223f65de2202842f6a19ce230744142ac56f84d4 and pick it if you like.

**Comment by AdamVerner** [comment]
Hey, superb work, i love the pair parsing.


> get I would use spaces (tab as delimiter) as default to improve readability for humans.

The tabs are great, but there's an issue with the output name. If your output name is long (NETIO4ALL supports up to 15 chars) other columns will be shifted.

e.g.:
```
id      Name    State   Action  Delay   Current PFactor Load    Energy
1       MyNetioOutput12 1       IGNORED 5000    0       0.0     0       2500
2       output_2        1       IGNORED 5000    0       0.0     0       2033
```

Now it looks like the current draw is 5000W Yikes!

 > After sleeping some more nights over the output from get I would use spaces (tab as delimiter) as default to improve readability for humans.

The reason for putting `;` there was because the name of the output differs in lenght so it breaks the columns, but that could be fixed by simply pushing the output name as last column. Done in 11db9a90.

<br>

Also while at it, i fixed config parsing so that the errors make more sense.

**Comment by sirhcel** [comment]
Likewise! Thank you Adam! :)

> The reason for putting `;` there was because the name of the output differs in lenght so it breaks the columns, but that could be fixed by simply pushing the output name as last column. Done in [11db9a9](https://github.com/netioproducts/PyNetio/commit/11db9a90c0dff5346db56d294afb6bb52b2c9c71).

Columns wider than 7 characters are the dilemma of tab-separating them. Putting the names at the end is a pretty elegant solution for that. Thumbs up!

The [last TODO](https://github.com/netioproducts/PyNetio/blob/11db9a90c0dff5346db56d294afb6bb52b2c9c71/Netio/cli.py#L166) I'm seeing in the CLI is about version output. When installing the package from a tarball
```
PyNetio$ python3 setup.py sdist bdist_wheel
PyNetio$ pip3 install --user dist/Netio-1.0.1-py3-none-any.whl
```
the output looks like what I'm expecting:
```
$ netio --version
netio (version 1.0.1)
```
The [action](https://github.com/netioproducts/PyNetio/blob/11db9a90c0dff5346db56d294afb6bb52b2c9c71/Netio/cli.py#L169) already looks like it does this job. Might this TODO be a leftover from previous edits?

Do you see points in need of some care before a release?

**Comment by AdamVerner** [comment]
added non-zero exit status and updated docs.
Will merge and release now, thanks a lot the work and ideas.

**Comment by sirhcel** [comment]
> Will merge and release now, thanks a lot the work and ideas.
Thank you Adam! Likewise! :)

**Pull request merged**
